# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pad',
            field=models.BooleanField(default=False, verbose_name='Pad instead crop image in teaser'),
        ),
    ]
